modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "offhandswitcher"
version = "${version}"
displayName = "OffHand Switcher Mod"
authors = "Sistr"
description = "オフハンドを切り替えできるModです。"
#logoFile = ""

[[dependencies.offhandswitcher]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.offhandswitcher]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.offhandswitcher]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
