modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "offhandswitcher"
version = "${version}"
displayName = "OffHand Switcher Mod"
authors = "Sistr"
description = "オフハンドを切り替えできるModです。"
#logoFile = ""

[[dependencies.offhandswitcher]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.offhandswitcher]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
